fix: fix error and typo in docker pylint and test, shell script
swsnu/swpp2020-team16 pull request #31
Opened 2020-10-30 15:48 UTC by ddongminstar

Update new format models with matching er-diagrams. 
Fix error and typo in docker-compose file and Dockerfile, shell scripts.

Resolve #30

2020-10-30 16:29 UTC, chullino requested changes
고생하셨습니다! 일단 requirements.txt관련 부분만 답변 해주시면 바로 approve할게요.

2020-10-30 16:29 UTC, chullino commented on etc/docker-scripts/backend/Dockerfile
> +RUN apt install -y libpq-dev python3-dev build-essential graphviz libgraphviz-dev pkg-config
👍

2020-10-30 16:29 UTC, chullino commented on coding-mbti/local-docker-starter-front/init.sh
> +    echo "[(3/3) docker-machine is not installed. please install.]"
🙇

2020-10-30 16:29 UTC, chullino commented on coding-mbti/backend/problem/models.py
> +        PJ = 4
여기 주석 달아주시면 좋을 듯 싶어요. 아직 초반이라 그런지 유형이 약어로 잘 안와닿아서요ㅠㅠ

2020-10-30 16:29 UTC, chullino commented on coding-mbti/backend/analysis/models.py
> +    JC = models.FloatField()
여기 주석 달아주세요!

2020-10-30 16:29 UTC, chullino commented on coding-mbti/backend/requirements.txt
> -psycopg2-binary==2.8.6
psycopg2-binary대신 psycopg2로 해도 괜찮았나요? reproducible problem이 아니긴 하지만, 환경설정할 때, psycopg2로 하니 진행이 안된 적이 있었고, 에러로그 힌트에 따라서 psycopg2-binary로 설치했었거든요.

2020-10-30 16:29 UTC, chullino commented on coding-mbti/backend/requirements.txt
> -idna==2.10
이거 다 지워도 괜찮나요? 아니면 다른 곳에서 처리해주셨나요?

2020-10-31 02:45 UTC, ddongminstar commented on coding-mbti/backend/requirements.txt
> -idna==2.10
예전 내용으로 복구 했어요

2020-10-31 02:45 UTC, ddongminstar commented on coding-mbti/backend/requirements.txt
> -psycopg2-binary==2.8.6
위에서 psycopg2로 설치하려고 libpq-dev, python3-dev 설치했었어요. 크게 상관은 없는거 같아요

2020-10-31 02:46 UTC, ddongminstar commented on coding-mbti/backend/analysis/models.py
> +    JC = models.FloatField()
넵

2020-10-31 02:46 UTC, ddongminstar commented on coding-mbti/backend/problem/models.py
> +        PJ = 4
넵

2020-10-31 03:46 UTC, chullino approved these changes

2020-10-31 03:54 UTC, merged