feat: Test page, Home IDE, ML features
swsnu/swpp2020-team16 pull request #54
Opened 2020-11-08 13:26 UTC by kwonsunbin

feat: Test page, Home IDE, ML features

2020-11-08 14:12 UTC, ddongminstar requested changes
backend에서 단순 코딩 스타일이랑 convention관련 내용이 있었고, 수정해서 다시 올려주시면 확인해드릴께요. 
front는 material-ui부분은 아직 잘 몰라서 리뷰를 못했고, redux store에서 작업하신 부분은 redux toolkit을 사용하도록 바꿔야해서, 우선 머지를 한다음에 제가 한번 일괄적으로 변경하고 확인하는게 어떤가요?

.pylintrc 파일, .eslintrc.js파일에서 linting 처리를 하면 코드가 더 이쁠꺼 같아요.

2020-11-08 14:12 UTC, ddongminstar commented on coding-mbti/backend/analysis/models.py
> +    class Meta:  # pylint: disable=too-few-public-methods
disable=too-few-public-methods 는 너무 걸리는 내용이 많고, django 모델 설계상 어쩔 수 없어서 pylintrc 파일에서 처리하는게 맞을꺼 같아요

2020-11-08 14:12 UTC, ddongminstar commented on coding-mbti/backend/analysis/models.py
> +    class Meta:  # pylint: disable=too-few-public-methods
같은 내용입니다.

2020-11-08 14:12 UTC, ddongminstar commented on .gitignore 3
> +.vscode/
.DS_Store 추가해주세요

2020-11-08 14:12 UTC, ddongminstar commented on coding-mbti/backend/analysis/views.py
> +        open(str(settings.BASE_DIR) + '/analysis/ML/problem{}/tf-idf_vectorizer.pickle'
f-string 으로 f'{setttings.ML_DIR}/problem{pid}/tf-idf_vectorizer.pickle'로 표현하면 이쁠거 같아요

2020-11-08 14:12 UTC, ddongminstar commented on coding-mbti/backend/analysis/views.py
> +        str(settings.BASE_DIR)+'/analysis/ML/problem{}/model_read.pkl'.format(pid))
같은 내용입니다.

2020-11-08 14:12 UTC, ddongminstar commented on coding-mbti/backend/analysis/views.py
> +    predict = int(clf_from_joblib.predict(
predict -> predicted_class, prediction, result_style

2020-11-08 14:12 UTC, ddongminstar commented on coding-mbti/backend/analysis/views.py
> +        str(settings.BASE_DIR)+'/analysis/ML/problem{}/model_style.pkl'.format(pid))
같은 내용입니다.

2020-11-08 14:12 UTC, ddongminstar commented on coding-mbti/backend/analysis/views.py
> +            # elapsed_time = json.loads(body)['elapsed_time']
코드에 주석은 없애주세요.

2020-11-08 14:12 UTC, ddongminstar commented on coding-mbti/backend/problem/models.py
> +    class Meta:  # pylint: disable=too-few-public-methods
diable too-few-public-methods는 .pylintrc파일에서 처리하면 좋을꺼 같아요.

2020-11-08 14:12 UTC, ddongminstar commented on coding-mbti/src/App.test.js
> +/* eslint-disable react/jsx-props-no-spreading */
.eslintrc.js 파일에서 한번에 처리하는게 좋아보여요

2020-11-08 14:12 UTC, ddongminstar commented on coding-mbti/src/components/CodeIDE.js
> +/* eslint max-len: ["error", { "code": 130 }] */
.eslintrc.js 파일에서 각자 처리하는게 이쁠꺼 같아요.

2020-11-08 14:12 UTC, ddongminstar commented on coding-mbti/src/store/actions/actionTypes.js
> +export const UPDATE_TEST_RESULT = 'UPDATE_TEST_RESULT';
redux toolkit 으로 작업하려고 해요. 한번 머지한다음에 제가 다 바꿔서 작업한걸로 올릴께요

2020-11-08 14:12 UTC, ddongminstar commented on package-lock 2.json
> +{
어떤 파일인가요?

2020-11-08 14:12 UTC, ddongminstar commented on coding-mbti/src/store/actions/test.js
> +/* eslint-disable import/prefer-default-export */
파일 이름으로 test.js는 좋지 못합니다.

2020-11-08 14:12 UTC, ddongminstar commented on package-lock 2.json
> +{
어떤 파일인가요?

2020-11-08 14:12 UTC, ddongminstar commented on package-lock.json
> +}
어떤 의미인가요?

2020-11-08 14:12 UTC, ddongminstar commented on coding-mbti/src/store/store.js
> +import {
redux toolkit 을 사용하는 버전으로 새로 올려드릴께요

2020-11-08 15:12 UTC, ddongminstar reviewed
좋습니다. @chullino 추가로 리뷰해 주세요.

2020-11-08 15:12 UTC, ddongminstar commented on coding-mbti/backend/.pylintrc
> +        too-few-public-methods
마지막에 ,로 끝내게 해주세요

2020-11-08 15:28 UTC, chullino requested changes
수고하셨습니다! 두어가지만 답변해주시고 바로 approve하도록 하겠습니다!

2020-11-08 15:28 UTC, chullino commented on coding-mbti/backend/requirements.txt
> +sklearn==0.23.2
여기수정 부탁드려요!

2020-11-08 15:28 UTC, chullino commented on coding-mbti/backend/requirements.txt
> +sklearn==0.23.2
scikit-learn이었지요 아마?

2020-11-08 15:28 UTC, chullino commented on coding-mbti/backend/analysis/tests.py
> +    "source_code":"n=int(input())\na=[[0 for i in range(13)]for j in range(4)]\nfor k in range(n):\ncard=input().split()\np=5\nif (card[0]=='S'):\np=0\nelif (card[0]=='H':\np=1\nelif (card[0]=='C'):\
이 데이터는 혹시 그 brython에서 받아오신 것인가요?

2020-11-08 15:28 UTC, chullino commented on coding-mbti/public/index.html
> +  </script>
여기 지워주시면  좋을 듯 싶어요!

2020-11-08 15:28 UTC, chullino commented on coding-mbti/src/components/Showprob.js
> +S 4
여기 데이터는 항상 보여져야 하는 부분인지, 아니면 데이터로 받아와야 하는 부분인지 궁금합니다!

2020-11-08 15:28 UTC, chullino commented on coding-mbti/src/index.js
> +import AlertTemplate from 'react-alert-template-basic';
이거 예쁘네요ㅎㅎ 👍

2020-11-08 15:28 UTC, chullino commented on coding-mbti/src/containers/Home.js
> +            output=" Print the missing cards. The same as the input format, each card should be printed with a character and an integer separated by a space character in a line. Arrange the missing c
나중에 데이터로 받아올 수 있게 처리하면 좋겠네요! 이번에 할 필요는 없지만, 이슈 끊어놓아주면 좋을 듯 싶어요!

2020-11-08 15:28 UTC, chullino commented on coding-mbti/src/containers/Check.js
> +            output=" Print the missing cards. The same as the input format, each card should be printed with a character and an integer separated by a space character in a line. Arrange the missing c
아래 써둔 것 처럼, 여기도 나중에 데이터로 받아올 수 있게 처리하면 좋겠어요! 이슈만 끊어주면 될 것이구, 이번 풀리퀘에서 처리 안하셔도 좋을 듯 싶어요!

2020-11-08 15:33 UTC, kwonsunbin commented on coding-mbti/src/components/Showprob.js
> +S 4
서버 쪽에 텍스트로 저장하거나, 데이터 베이스에 문제들 보관해뒀다가 불러오는 식으로 할 계획이긴했습니다.

2020-11-08 15:34 UTC, kwonsunbin commented on coding-mbti/backend/analysis/tests.py
> +    "source_code":"n=int(input())\na=[[0 for i in range(13)]for j in range(4)]\nfor k in range(n):\ncard=input().split()\np=5\nif (card[0]=='S'):\np=0\nelif (card[0]=='H':\np=1\nelif (card[0]=='C'):\
아니요 데이터 그 aizu 대학교 온라인 코딩 사이트에서 가져왔습니다

2020-11-08 15:42 UTC, kwonsunbin commented on coding-mbti/src/components/Showprob.js
> +S 4
이 부분이 보여질 때 줄 바꿈이 필요하여 각 줄마다 \n 추가해서 property로 전달한 다는것이 깜빡했네요... 이슈걸어두고 다음 번에 수정하겠습니다!

2020-11-08 15:51 UTC, chullino commented on coding-mbti/backend/analysis/tests.py
> +    "source_code":"n=int(input())\na=[[0 for i in range(13)]for j in range(4)]\nfor k in range(n):\ncard=input().split()\np=5\nif (card[0]=='S'):\np=0\nelif (card[0]=='H':\np=1\nelif (card[0]=='C'):\
확인했습니다~!

2020-11-08 15:51 UTC, chullino commented on coding-mbti/src/components/Showprob.js
> +S 4
알겠습니다!

2020-11-08 16:24 UTC, chullino approved these changes

2020-11-09 05:55 UTC, ddongminstar approved these changes

2020-11-09 05:58 UTC, merged