Implementation example front
swsnu/swpp2020-team16 pull request #72
Opened 2020-11-17 07:15 UTC by chullino

2020-11-18 14:29 UTC, ddongminstar requested changes
두가지만 처리해주세요

2020-11-18 14:29 UTC, ddongminstar commented on coding-mbti/src/containers/Check.js
> +    await this.props.readProblemOutput(this.props.match.params.pid);
Promise.all 로 고쳐주세요 비동기 여러번 보내는건 부적절합니다.

2020-11-18 14:29 UTC, ddongminstar commented on coding-mbti/src/feature/user/userSignSlice.js
> +};
await 과 then이 중복되있습니다. await으로 처리해주세요

2020-11-21 11:54 UTC, chullino commented on coding-mbti/src/containers/Check.js
> +    await this.props.readProblemOutput(this.props.match.params.pid);
처리했어요!

2020-11-21 11:54 UTC, chullino commented on coding-mbti/src/feature/user/userSignSlice.js
> +};
처리했어요!

2020-11-21 12:20 UTC, ddongminstar approved these changes
좋습니다.

2020-11-21 12:20 UTC, merged